In [3]:
! pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [4]:
#using array function to create an array 
x=np.array([1,2,3,4,5,6,5.5])
print(type(x))

<class 'numpy.ndarray'>


In [5]:
#using array function to create an array 
x=np.array([1,2,3,4,5,6,5.5])
print(x)

[1.  2.  3.  4.  5.  6.  5.5]


In [6]:
#using .arrange method
a=np.arange(4)
print(a)

[0 1 2 3]


In [7]:
a=np.arange(-10,-4,1)
print(a)

[-10  -9  -8  -7  -6  -5]


In [8]:
a=np.arange(-10,-4,-1)
print(a)

[]


In [9]:
a=np.arange(10,-4,-20)
print(a)

[10]


In [10]:
#creates array with random values
a1=np.random.random(size=(4,3)) 
print(a1)

[[0.80062774 0.76031281 0.8259271 ]
 [0.7728617  0.02151702 0.18355719]
 [0.16903368 0.68844288 0.46569989]
 [0.04006584 0.36747866 0.30067207]]


In [11]:
x1=np.random.randint(50,size=6) #1D
x2=np.random.randint(10,size=(3,4)) #2D
x3=np.random.randint(10,size=(3,4,5)) #3D
print(x1)
print()
print(x2)
print()
print(x3)

[ 3 47  8  1 14  8]

[[9 3 7 5]
 [0 7 7 4]
 [8 8 7 3]]

[[[3 1 9 2 5]
  [2 0 0 6 2]
  [2 7 6 8 3]
  [6 8 4 0 7]]

 [[7 0 2 4 1]
  [6 5 4 5 8]
  [2 4 5 1 0]
  [5 9 3 2 7]]

 [[5 2 7 8 8]
  [9 7 0 3 8]
  [2 0 6 6 2]
  [2 4 3 0 8]]]


In [13]:
#0(Zero)-D arrays,or Scalars are the elements in an array .each value in an array is a zero dimensional

In [14]:
arr=np.array([42])
print(arr)
print('Dimensions : ',arr.ndim)

[42]
Dimensions :  1


In [15]:
arr=np.array([1,2,3,4,5])
print(arr)
print('Dimensions : ',arr.ndim)

[1 2 3 4 5]
Dimensions :  1


In [16]:
data2=[[1,2,3,4],[6,7,8,9]]
arr2=np.array(data2)
print(arr2)
print('Dimensions : ',arr2.ndim)

[[1 2 3 4]
 [6 7 8 9]]
Dimensions :  2


In [17]:
arr3=np.random.randint(50,size=(3,4,5))
print(arr3)
print('Dimensions : ',arr3.ndim)

[[[13 17 25 33  8]
  [21 24 19  9  6]
  [41 29  3  2 35]
  [ 5 31 14 19 21]]

 [[22 15 22 13 49]
  [48 25 37 31 44]
  [ 8 42 26 28 10]
  [33 42 49  1 48]]

 [[44 15 27 38 10]
  [28  0 24 24 14]
  [16  4 34 24 32]
  [19 49 33  4  2]]]
Dimensions :  3


In [18]:
arr4=np.random.randint(50,size=(3,4,5,2))
print(arr4)
print('Dimensions : ',arr4.ndim)

[[[[48  7]
   [ 7  3]
   [11 43]
   [10 45]
   [49 19]]

  [[ 4  5]
   [43 41]
   [23 20]
   [25 18]
   [40 23]]

  [[41  1]
   [29  1]
   [16 46]
   [17 34]
   [13 30]]

  [[47 16]
   [15 23]
   [31  5]
   [33 11]
   [20  5]]]


 [[[ 4 10]
   [ 8 30]
   [19 35]
   [39  5]
   [ 6 26]]

  [[34  0]
   [40  1]
   [18 33]
   [42 37]
   [14 30]]

  [[21 37]
   [15  8]
   [23 37]
   [22 26]
   [19 25]]

  [[17 21]
   [ 1  8]
   [26 44]
   [25 24]
   [19 33]]]


 [[[41 33]
   [23 35]
   [21  3]
   [18 14]
   [38 46]]

  [[25  6]
   [24 25]
   [ 9 40]
   [31 38]
   [18 27]]

  [[25 42]
   [41 46]
   [22  8]
   [24 42]
   [31 26]]

  [[ 0 49]
   [20 16]
   [37  6]
   [47  2]
   [29 28]]]]
Dimensions :  4


In [19]:
#Reshape method
arr1=np.arange(10)
arr2=np.arange(12).reshape(3,4)
arr3=np.arange(24).reshape(2,4,3)
print(arr1)
print()
print(arr2)
print()
print(arr3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [20]:
print(arr1[2::2])
print(arr1[::])
print(arr1[::-1])

[2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [21]:
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
arr2[1::,::2]

array([[ 4,  6],
       [ 8, 10]])

In [ ]:
print(arr2[0,:])
print()
print(arr2[:,0])
print()
print(arr2[1:,1:])
print()
print(arr2[0::2,:2:])

[0 1 2 3]

[0 4 8]

[[ 5  6  7]
 [ 9 10 11]]

[[0 1]
 [8 9]]


In [24]:
print(arr2[1::1,1::2])

[[ 5  7]
 [ 9 11]]


In [25]:
arr3=np.arange(24).reshape(2,4,3)
print(arr3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [38]:
print(arr3[:,::3,::2])
print()
print(arr3[::-1,-2::-2,-1::-2])

[[[ 0  2]
  [ 9 11]]

 [[12 14]
  [21 23]]]

[[[20 18]
  [14 12]]

 [[ 8  6]
  [ 2  0]]]


In [41]:
arr3[::-1,-2::-1,-2::-1]

array([[[19, 18],
        [16, 15],
        [13, 12]],

       [[ 7,  6],
        [ 4,  3],
        [ 1,  0]]])

In [26]:
print(arr3[0],end='\n\n')
print(arr3[0,0],end='\n\n')
print(arr3[1,:3],end='\n\n')
print(arr3[0,:2,::2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[0 1 2]

[[12 13 14]
 [15 16 17]
 [18 19 20]]

[[0 2]
 [3 5]]


In [27]:
arr3[1,1::2,::2]

array([[15, 17],
       [21, 23]])

In [ ]:
#Attribute
a1=np.array([1,2,3,4])
a2=np.array([1,1,2.2,3.3,4.4])
#here "dtype" specifies  the type of the element contained in the array
print(a1.dtype)
print(a2.dtype)
#number of bytes occupied by individual array are available through itemsize
print(a1.itemsize)
print(a2.itemsize)
#number of bytes occupied by entire are available through "itemsize"
print(a1.nbytes)
print(a2.nbytes)

int64
float64
8
8
32
40


In [44]:
a1=np.array([1,2,3,4])
a2=np.array([[1,2,3,4],[5,6,7,8]])
print(a1.ndim)
print(a2.ndim)

print(a1.shape)
print(a2.shape)

print(a1.size)
print(a2.size)

1
2
(4,)
(2, 4)
4
8


In [45]:
#numpy array function
#ones create array of 0's
print(np.zeros(10,dtype='int'))
print()
print(np.zeros((3,6),dtype='int'))
print()
print(np.zeros((2,3,2)))

[0 0 0 0 0 0 0 0 0 0]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
#ones create array of 1's
print(np.ones(10,dtype='int'))
print()
print(np.ones((3,6)))
print()
print(np.ones((2,3,2)))

[1 1 1 1 1 1 1 1 1 1]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [41]:
np.identity(4) # default data as float

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [2]:
a1=np.array([1,3,5,7])
a2=np.array([2,4,6,8])
print(a1)
print(a2)

[1 3 5 7]
[2 4 6 8]


In [3]:
#All scalar operation on 1D array using operation
print(a1+5)
print(a1-5)
print(a1*2)
print(a1/2)
print(a1//2) #flow division gives int value
print(-a1)
print(a1**2)
print(a1%2)

[ 6  8 10 12]
[-4 -2  0  2]
[ 2  6 10 14]
[0.5 1.5 2.5 3.5]
[0 1 2 3]
[-1 -3 -5 -7]
[ 1  9 25 49]
[1 1 1 1]


In [4]:
#All vector operation on 1D array using operation
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1//a2)
print(a1**a2)
print(a1%a2)

[ 3  7 11 15]
[-1 -1 -1 -1]
[ 2 12 30 56]
[0.5        0.75       0.83333333 0.875     ]
[0 0 0 0]
[      1      81   15625 5764801]
[1 3 5 7]


In [6]:
#DOT PRODUCT
#1D array
arr1=np.array([9,10,20])
arr2=np.array([2,5,7])

np.dot(arr1,arr2)

np.int64(208)

In [5]:
#2D array
arr1=np.arange(12).reshape(3,4)
arr2=np.arange(12).reshape(4,3)

np.dot(arr1,arr2)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [9]:
#statisatic
# IN NUMPY X=0 COLOUMN 
# AND X=2 ROW
x=np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
np.mean(x)

np.float64(9.5)

In [ ]:
np.mean(x,axis=0) #colomn wise mean

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [12]:
np.mean(x,axis=1) #row wise mean

array([ 2.,  7., 12., 17.])

In [13]:
np.min(x)

np.int64(0)

In [14]:
np.max(x)

np.int64(19)

In [ ]:
np.min(x,axis=0) #calculate colomn wise min

array([0, 1, 2, 3, 4])

In [ ]:
np.min(x,axis=1) # calculate row wise min

array([ 0,  5, 10, 15])

In [ ]:
np.max(x,axis=0) #calculate column wise max

array([15, 16, 17, 18, 19])

In [ ]:
np.max(x,axis=1) # calculate row wise max

array([ 4,  9, 14, 19])

In [ ]:
np.sum(x) #calculate the sum of array

np.int64(190)

In [21]:
np.sum(x,axis=0) #calculate column wise sum

array([30, 34, 38, 42, 46])

In [22]:
np.sum(x,axis=1) #calculate row wise sum

array([10, 35, 60, 85])

In [23]:
p25=np.percentile(x,25)
p50=np.percentile(x,50)
p75=np.percentile(x,75)
p100=np.percentile(x,100)
print()
print("25th Percentile: ",p25)
print("50th Percentile: ",p50)
print("75th Percentile: ",p75)
print("100th Percentile: ",p100)


25th Percentile:  4.75
50th Percentile:  9.5
75th Percentile:  14.25
100th Percentile:  19.0


In [24]:
#iterating through an array
#1D array
a1=np.array([2,4,6,7,8,9,1,2,3])
for i in a1:
    print(i,end=" ")

2 4 6 7 8 9 1 2 3 

In [26]:
#2D array
a2=np.arange(20).reshape(4,5)
# print(a2)
for i in a2:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [28]:
a2=np.arange(20).reshape(4,5)
cnt=5
for i in range(len(a2)):
    a2[i]+=cnt
    cnt+=5
print(a2)

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]]


In [29]:
#STACKING OF NUMPY ARRAY
s1=np.arange(12).reshape(3,4)
s2=np.arange(12,24).reshape(3,4)


In [30]:
s1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
s2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
#horizontal stacking
s3=np.hstack((s1,s2))
s3

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [34]:
#vertical stacking
s4=np.vstack((s1,s2))
s4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#SPLITING OF NUMPY ARRAY
np.hsplit(s3,2) 

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [36]:
np.hsplit(s3,4)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [37]:
np.hsplit(s3,8)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]]),
 array([[14],
        [18],
        [22]]),
 array([[15],
        [19],
        [23]])]

In [38]:
np.vsplit(s3,3)

[array([[ 0,  1,  2,  3, 12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7, 16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 20, 21, 22, 23]])]

In [40]:
s4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
np.vsplit(s4,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [42]:
np.vsplit(s4,6)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [44]:
np.vsplit(s4,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [45]:
#wap which makes an array having corresponding max value out of given two arrays
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])                           #output[6,3,1,7,2]
lst=[]
for i in range(len(a)):
    lst.append(max(a[i],b[i]))
print(np.array(lst))

[6 3 1 7 8]
